version: "3"

services:
  redis-server:
    container_name: redis-server
    image: 'redis'
    ports:
      - 6379:6379
  node-app:
    build: .
    container_name: node-app
    restart: always
    volumes:
        - ./:/usr/app
        - /app/node_modules
    ports:
      - 8080:8080
    links:
      - redis-server
