version: "3"

services:
  redis-server:
    container_name: redis-server
    image: 'redis'
    ports:
      - 6379:6379
  node-app:
    container_name: node-app
    restart: always
    image: node:alpine
    volumes:
        - ./:/usr/src/app:cached
        - ./node_modules:/usr/src/app/node_modules:cached
    working_dir: /usr/src/app
    command: sh -c "npm i && npm start"
    ports:
      - 8080:8080
    links:
      - redis-server
  